### ISSUE TITLE
Error when running `php artisan migrate`

### ISSUE THREAD

**Issue by dillfrescott** [leventdev/dropspace#27]
```
root@cross-minisrv:/dropspace# php artisan migrate

   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema = dropspace and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:716
    712▕         // If an exception occurs when attempting to run a query, we'll format the error
    713▕         // message to include the bindings with SQL, which will make this exception a
    714▕         // lot more helpful to the developer instead of just the database's errors.
    715▕         catch (Exception $e) {
  ➜ 716▕             throw new QueryException(
    717▕                 $query, $this->prepareBindings($bindings), $e
    718▕             );
    719▕         }
    720▕     }

      +33 vendor frames 
  34  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by leventdev** [comment]
Seems like something with your DB?

I'd try the following options:
1. Try php artisan migrate:fresh

2. Check if the port, host matches the server.

3. Check if the user has correct permissions.


These are the options that pop into my head, but i'm not in front of a computer to actually check them.

**Comment by dillfrescott** [comment]
Ok. Ill have to work out whats wrong with the db!

**Comment by dillfrescott** [comment]
I absolutely cannot get this app to run. I've tried three or 4 different databases and they all throw a similar error. Even on the docker container that I never even modified...

**Comment by leventdev** [comment]
Have you installed it following the readme? Do you have the right DB extensions installed for php?

**Comment by dillfrescott** [comment]
I'll have to check the docker container. I'd like to assume so but I guess you never know till you check haha
